### ISSUE TITLE
Email address on website returns MAILER-DAEMON error

### ISSUE THREAD

**Issue by dalDevelo** [iina/iina-website#3]
I'm not sure if this is the correct place to report this, but I've attempted to email developers@iina.io, which is the contact address listed on the site, but I am getting a MAILER-DAEMON message which returns the following error...

Sorry, we were unable to deliver your message to the following address.

<developers@iina.io>:
550: 5.7.1 Service unavailable

**Comment by lhc70000** [comment]
It might be a temporary network error. Does the problem persist now?

**Comment by dalDevelo** [comment]
Received a response. Thanks @lhc70000, as you said, it was probably a temporary error. Closing the issue now.
